spring:
  application:
    name: prediction-backend-api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ds:
  api:
    base-url: http://ec2-3-134-85-182.us-east-2.compute.amazonaws.com:8000/
